# Generated by Django 2.2.26 on 2022-03-24 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20220324_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='uid',
        ),
    ]
