# Generated by Django 2.2.26 on 2022-03-23 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20220323_1253'),
        ('store', '0002_auto_20220323_1454'),
    ]

    operations = [
    ]
